cg5580-a4/src/A4cg5580/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.ico')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cg5580-a4/src/posts/urls.py
from django.urls import path
from .views import (
    post_list_and_create,
    load_post_data_view,
    like_unlike_post,
    post_detail,
    post_detail_data_view,
    update_post,
    delete_post,
    image_upload_view,
    create_comment,
)

app_name = 'posts'

urlpatterns = [
    path('', post_list_and_create, name='main-board'),
    path('like-unlike/', like_unlike_post, name='like-unlike'),
    path('upload/', image_upload_view, name='image-upload'),
    path('<pk>/', post_detail, name='post-detail'),
    path('<pk>/update/', update_post, name='post-update'),
    path('<pk>/delete/', delete_post, name='post-delete'),
    path('<pk>/comment/', create_comment, name='create-comment'),

    path('data/<int:num_posts>/', load_post_data_view, name='post-data'),
    path('<pk>/data/', post_detail_data_view, name='post-detail-data'),
]

cg5580-a4/src/profiles/urls.py
from django.urls import path
from .views import my_profile_view
app_name = 'profiles'

urlpatterns = [
    path('my/', my_profile_view, name='my-profile'),
]

cg5580-a4/src/templates/base.html
{% load static %}
<! doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <!-- favicon -->
        <link rel="icon" type="image/png" href="{% static 'favicon.ico' %}"/>

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet">
        <!-- Custom CSS -->
        <link rel="stylesheet" href="{% static 'style.css' %}">

        <!-- DropZone-->
        <script src="https://cdn.jsdelivr.net/npm/dropzone@5/dist/min/dropzone.min.js"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/dropzone@5/dist/min/dropzone.min.css" type="text/css" />

        <!-- Custom JS -->
        <script src="{% static 'functions.js' %}" defer></script>
        {% block scripts %}
        {% endblock scripts %}
        
        <title> Read Posts | {% block title %} {% endblock title %}</title>
    </head>
    <body>
        {% include "navbar.html" %}
        <div class="container mt-3 mb-3">
            {% block content %}
            {% endblock content %}
        </div>
        
        <!-- Bootstrap Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"></script>
        <!-- JQuery -->
        <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    </body>
</html>

cg5580-a4/src/templates/navbar.html
{% url 'posts:main-board' as path_to_home %}
{% url 'profiles:my-profile' as path_to_my_profile %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{path_to_home}}">Posts-proj</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link {% if request.path == path_to_home %}active{% endif %}" href="{{path_to_home}}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == path_to_my_profile %}active{% endif %}" href="{{path_to_my_profile}}">My Profile</a>
        </li>
      </ul>
    </div>
  </div>
</nav>